### ISSUE TITLE
md error in 2023-01-19-how-to-build-a-nostr-gm-bot.md

### ISSUE THREAD

**Issue by gourcetools** [dergigi/dergigi.github.io#451]
**6) Say "Good morning!"**
...`
{% include image.html name="event.png" caption="Be [kind 1](https://github.com/nostr-protocol/nips/blob/master/01.md#basic-event-kinds), for everyone you meet is fighting a hard battle." link=" `

7) Automate with crontab

I think there is a problem here:

![image](https://user-images.githubusercontent.com/120996278/213586667-49b91a5b-cd7c-4249-9812-5f108090e74d.png)

good luck :) nice tutorial
cya. bitpaint

**Comment by gourcetools** [comment]
also at the very end
![image](https://user-images.githubusercontent.com/120996278/213832249-416f5cb1-1f1e-4324-b76f-0235ba36e7cd.png)

**Comment by dergigi** [comment]
Thanks for reporting! I think I fixed both soon after. I need to get better at checking github issue 😅 Thanks again!
